### ISSUE TITLE
Missing instructions for "Your guess is too short"

### ISSUE THREAD

**Issue by Steve-Z** [csev/wa4e#3]
https://github.com/csev/wa4e/blob/ec3a11c7acc542d5f3b4fd71bff7fb78408ca57c/assn/guess/index.php#L67

In `<ul>` should add instructions for "Guess is too short" since auto-grader looks for this:
`strlen($_GET['guess']) < 1`

**Comment by srcatto** [comment]
This test is already in the forms.zip/guess.php starter code. Since at least a zip I have downloaded dated 19 Aug 2017, and the date on guess.php of 26 Jan 2017. There is no requirement to write code from scratch. As well as too many do's and dont's to specify everything needed in the instructions. The specialization uses the starter code as building blocks for every assignment.

**Comment by Steve-Z** [comment]
Closed based on @srcatto comment above.
